version: "3"

services:

  redis:
    image: redis:5
    command: redis-server
    ports:
    - "6379:6379"
    restart: always 

  # rabbitmq:   # for distributed web crawling  one day
  #   image:  rabbitmq:3.7.3-management
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"    

  postgres:  # hostname
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres  # username, maintenance
      POSTGRES_PASSWORD: changeme  # password
      PGDATA: /data/postgres
    volumes:
        - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: always 
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      SCRIPT_NAME: /pgadmin4
    volumes:
        - pgadmin:/root/.pgadmin
    expose:
      - "80"
    restart: always 

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/static:/usr/share/nginx/html/static
      - ./nginx/ssl:/usr/share/nginx/ssl 
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx 
    depends_on:
      - web
    restart: always

  web:
    build: ./backend
    command: >
      sh -c "./start.sh"   
    expose:
      - "8000"
      - "5555"                      
    volumes:
      - /etc/localtime:/etc/localtime  # sync time to local computer 
      - ./backend:/crawl
    depends_on: 
      - redis
      # - rabbitmq
      - postgres
    restart: always    


    
volumes:
  postgres:
  pgadmin: 
